apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "taskflow.fullname" . }}-clickhouse-pvc
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.storage }}
