apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskflow.fullname" . }}-clickhouse
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels" . | nindent 6 }}
      app: clickhouse
  template:
    metadata:
      labels:
        {{- include "taskflow.selectorLabels" . | nindent 8 }}
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: {{ .Values.clickhouse.image }}
          env:
            - name: CLICKHOUSE_DEFAULT_PASSWORD
              value: ""
          ports:
            - containerPort: 8123
            - containerPort: 9000
          volumeMounts:
            - name: clickhouse-storage
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: {{ include "taskflow.fullname" . }}-clickhouse-pvc
